### PR TITLE
fixed ``id-ID`` to ``id``

### PR DESCRIPTION
**Pull request by soevielofficial**
if the user uses Indonesian in the web browser, the website will automatically be in Indonesian.

image

image

Thanks to @mingroushen for the feedback and suggestions

### CODE REVIEW

**Comment by xinyihl** [comment]
This depends on your browser settings.
Just like the first one below is `en` second one is `en-US`.
image

**Comment by xinyihl** [comment]
if you want fix i suggest
```
  switch(navigator.language.substring(0,2))
  {
      case 'zh':window.location="zh.html";break;
      case 'id':window.location="id.html";break;
      default:window.location="en.html";break;
  }
```

**Review by soevielofficial — COMMENTED** [review]
this good,, I think this source code provides a simple way to redirect users to a localized version of a website based on their browser language preferences.

**Comment by soevielofficial** [comment]
the code checks the first two characters of the string returned by ``navigator.language`` (which represents the user's preferred language in their browser settings) using the ``substring()`` method.

if the language is Chinese (represented by 'zh'), the user will be redirected to a webpage named "zh.html". if the language is Indonesian (represented by 'id'), the user will be redirected to a webpage named "id.html". for any other language, the user will be redirected to a webpage named "en.html".

**Pull request merged**
